services:
  # nginx:
  #   image: nginx:alpine
  #   ports:
  #     - "80:80"
  #     - "443:443"
  #   networks:
  #     - eskol_net
  #   depends_on:
  #     - frontend
  #     - backend
  #     - wordpress

  backend:
    build:
      context: ./backend
    env_file:
      - .env
    ports:
      - "8084:8000"
    volumes:
      - ./backend:/app
    networks:
      - eskol_net
    depends_on:
      mariadb:
        condition: service_healthy

  frontend:
    build:
      context: ./frontend
      args:
        - VITE_API_URL=${VITE_API_URL}
        - VITE_APP_URL=${VITE_APP_URL}
    ports:
      - "8083:80"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - eskol_net

  wordpress:
    image: wordpress:latest
    env_file:
      - .env
    ports:
      - "8082:80"
    volumes:
      - ./data/wordpress:/var/www/html
    networks:
      - eskol_net
    depends_on:
      mariadb:
        condition: service_healthy

  mariadb:
    image: mariadb:10.11
    env_file:
      - .env
    volumes:
      - ./data/mariadb:/var/lib/mysql
    networks:
      - eskol_net
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 10s
      timeout: 5s
      retries: 5

  mongo:
    image: mongo:7
    env_file:
      - .env
    volumes:
      - ./data/mongodb:/data/db
    networks:
      - eskol_net

  phpmyadmin:
    image: phpmyadmin:latest
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mariadb
    networks:
      - eskol_net
    depends_on:
      - mariadb

  n8n:
    image: n8nio/n8n
    ports:
      - "8085:5678"
    volumes:
      - ./data/n8n:/home/node/.n8n
    env_file:
      - .env
    networks:
      - eskol_net

networks:
  eskol_net:
    name: eskol_net
    driver: bridge
